spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/shop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging.level:
  org.hibernate.SQL: debug