spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/shop
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useSSL=false&serverTimeZone=Asia/Seoul&characterEncoding=utf-8
    username: root
    password: Cyujin4641!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        # default_batch_fetch_size: 1000 #최적화 옵션

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging.level:
  org.hibernate.SQL: debug

server:
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie